# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#top-level-configuration
version: v2025.01.0
tutorial: false

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

private:
  keys:
    entsoe_api:

remote:
  ssh: ""
  path: ""

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: ""
  name: ""
  scenarios:
    enable: false
    file: config/scenarios.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  shared_cutouts: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: myopic

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  clusters:
  - 39
  opts:
  - ''
  sector_opts:
  - ''
  planning_horizons:
  - 2030

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'XK']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#snapshots
snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: 'left'

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: auto
  retrieve_databundle: true
  retrieve_cost_data: true
  build_cutout: false
  retrieve_cutout: true
  custom_busmap: false
  drop_leap_day: true
  procurement: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#electricity
electricity:
  max_hours:
    li-ion battery: [8]
    vanadium: [10]
    lair: [12]
    pair: [24]
    H2: [168]
    iron-air battery: [100]

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  transport: false
  heating: false
  biomass: false
  industry: false
  agriculture: false
  fossil_fuels: true
#  stores: ["H2"]
#  storage_units: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#costs
costs:
  year: 2025
  version: v0.11.1

  fuel:
    OCGT: 38.84 # https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:52022SC0230 (Annex)
    CCGT: 38.84
    gas: 38.84
    coal: 24.57 # https://businessanalytiq.com/procurementanalytics/index/subbituminous-coal-price-index/
    lignite: 22.11 # https://businessanalytiq.com/procurementanalytics/index/lignite-coal-price-index/
    nuclear: 1.75 # https://markets.businessinsider.com/commodities/uranium-price
    uranium: 1.75
  efficiency:
    Compressed-Air-Adiabatic-bicharger: 0.7745
  investment:
    iron-air battery: 21710  # in EUR/MWh (2020) from 23,500 EUR/MWh (2024)
    Compressed-Air-Adiabatic-store: 28835  # in EUR/MWh (2020) from 30,000 EUR/MWh (2022)
    Compressed-Air-Adiabatic-bicharger: 1658016  # in EUR/MW (2020) from 1,725,000 EUR/MW (2022)
  lifetime:
    Compressed-Air-Adiabatic-store: 40  # years
    Compressed-Air-Adiabatic-bicharger: 40  # years
  marginal_cost:
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 0.
    electrolysis: 0.
    fuel cell: 0.
    li-ion battery: 0.
    battery inverter: 0.
  emission_prices:
    enable: false
    co2: 0.
    co2_monthly_prices: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering
clustering:
  temporal:
    resolution_sector: 1H


###################
# Procurment Metastudy

procurement:
  stratergy: # "ref", "cfe90", "cfe98", "cfe100", "cfe..", "res90", "res98", "res100", "res.."
  zone: "DE" # "node", "country", "all"
  participation: 10

  strip_network: true

  ci:
    Germany: # Set name here
      location: "DE0 0" # "PT1 0"
      load: 3841 # in MWh
      profile: "baseload" # "datacenter", "industry" or custom in data/ci_profile.csv
  
  ci_setting:
    excess_share: 0.  # share of excess CI generation that can be sold to the grid [percentage]
    flexibility: 0. # possible deviation of requested load from nominal level [percentage of nominal load]
    spatial_shifting: false #turns on/off spatial flexibiilty  (aka virtual links)
    temporal_shifting: false #turns on/off temporal flexibiilty (aka DSM)
  
  technology:
    generation_tech: ["onwind", "solar", "nuclear", "allam", "geothermal"]
    storage_tech: ["li-ion battery", "vanadium", "lair", "pair", "iron-air battery"]
    storage_component: # Store, StorageUnit

  grid_policy:
    renewable_carriers: ["offwind", "offwind-ac", "offwind-dc", "onwind", "ror", "solar", "hydro", "urban central solid biomass CHP"] #"solar rooftop"
    clean_carriers: ["offwind", "offwind-ac", "offwind-dc", "onwind", "ror", "solar", "hydro", "nuclear", "urban central solid biomass CHP"] #"solar rooftop"
    emmiters: ["CCGT", "OCGT", "coal", "lignite", "oil"]

RES_target:
  2025:
    IE: 0.47
    DK: 0.85  # p.3 https://ens.dk/sites/ens.dk/files/Basisfremskrivning/kf23_sektornotat_8b_forbrug_af_el.pdf
    DE: 0.65   # actual realisation. Plan is lower https://www.diw.de/de/diw_01.c.841560.de/ampel-monitor_energiewende.html#ab_842744
    NL: 0.49   # interpolated from 2020 wind+solar 19%, bioenergy 6% to 2030 target
    AT: 0.90   # 79% overall renewables in 2020 -> target 100% 2030
    BE: 0.323  # p.63 https://energy.ec.europa.eu/system/files/2020-09/be_final_necp_parta_en_0.pdf, 11.156 GWh = 32.3%
    BG: 0.21   # p. 59 Figure 10 https://energy.ec.europa.eu/system/files/2020-06/bg_final_necp_main_en_0.pdf
    CZ: 0.14   # 4% wind+solar 2020, 12% renewable overall (2020)
    HR: 0.56   # interpolated Table 2-1 p.54 https://energy.ec.europa.eu/system/files/2020-01/hr_final_necp_main_en_0.pdf
    FR: 0.32   # 10% wind+solar 2020, 23% renewable overall
    GB: 0.535  # interpolated from 2020: 29% wind + solar 2020, 42% renewable overall to 2030 target
    PL: 0.245  # 11% wind + solar 2020, 17% renewable overall
    ES: 0.588  # linear interpolated share 46.6% in 2021 targer 74% in 2030
    PT: 0.69   # p.41 Table 9 https://energy.ec.europa.eu/system/files/2020-06/pt_final_necp_main_en_0.pdf
  2030:
    IE: 0.7
    DK: 1.17  # https://ens.dk/sites/ens.dk/files/Basisfremskrivning/kf23_sektornotat_8b_forbrug_af_el.pdf
    DE: 0.80  # https://www.bmwk.de/Redaktion/EN/Downloads/Energy/0406_ueberblickspapier_osterpaket_en.html
    NL: 0.73  # https://energy.ec.europa.eu/system/files/2021-01/staff_working_document_assessment_necp_netherlands_en_0.pdf
    AT: 1.0   # https://windeurope.org/newsroom/news/austria-aims-to-have-100-renewable-electricity-by-2030/
    BE: 0.37  # https://energy.ec.europa.eu/system/files/2020-09/be_final_necp_parta_en_0.pdf
    BG: 0.27  # p.59 Figure 10 https://energy.ec.europa.eu/system/files/2020-06/bg_final_necp_main_en_0.pdf
    HR: 0.64  # p.54 Table 2-1 https://energy.ec.europa.eu/system/files/2020-01/hr_final_necp_main_en_0.pdf
    CZ: 0.17
    FR: 0.4
    GB: 0.65  # https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/938539/NIS_Report_Web_Accessible.pdf
    PL: 0.32  # table 1.1 https://iea.blob.core.windows.net/assets/b9ea5a7d-3e41-4318-a69e-f7d456ebb118/Poland2022.pdf
    ES: 0.74  # p.10 https://energy.ec.europa.eu/system/files/2021-01/staff_working_document_assessment_necp_spain_en_0.pdf
    PT: 0.8   # p.41 Table 9 https://energy.ec.europa.eu/system/files/2020-06/pt_final_necp_main_en_0.pdf

solving:
  options:
    min_iterations: 2

  constraints:
    RES: True

