# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#top-level-configuration
version: v2025.01.0
tutorial: false

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

private:
  keys:
    entsoe_api:

remote:
  ssh: ""
  path: ""

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: ""
  name:
  #- baseline-2025-3H
  - baseline-2030-3H
  scenarios:
    enable: true
    file: config/scenarios.meta-3H.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  shared_cutouts: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: myopic

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  clusters:
  - 39
  opts:
  - ''
  sector_opts:
  - ''
  planning_horizons:
  # - 2025
  - 2030

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'XK']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#snapshots
snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: 'left'

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: auto
  retrieve_databundle: false
  retrieve_cost_data: true
  build_cutout: false
  retrieve_cutout: false
  custom_busmap: false
  drop_leap_day: true
  procurement: true  # [true, false ] If true, model the procurement strategies
  ci_load: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#electricity
electricity:
  max_hours:
    li-ion battery: [8]
    vanadium: [10]
    lair: [12]
    pair: [24]
    H2: [168]
    iron-air battery: [100]

  extendable_carriers:
    StorageUnit: [] # li-ion battery, iron-air battery, H2, lfp, vanadium, lair, pair
    Store: [li-ion battery, H2]

  powerplants_filter: >
    (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'DE' and Fueltype == 'Nuclear')
    and not (Country.isin(['AT', 'BE', 'DK', 'ES', 'FI', 'FR', 'GB', 'GR', 'HU', 'IE', 'IT', 'MK', 'NL', 'PT', 'RS', 'SE', 'SK'])
    and Fueltype.isin(['Hard Coal', 'Lignite']))

  transmission_limit: v1.0

  ci_load:
    load_path_1: data/CI-load.csv # path to Eurostat CI load input data (from https://ec.europa.eu/eurostat/databrowser/view/nrg_cb_e__custom_16270810/default/table?lang=en (CSV 2.0))
    load_path_2: data/CI-load-missing.xlsx # path to IEA CI load input data (from https://www.iea.org/data-and-statistics/data-product/world-energy-balances-highlights)
    load_year: 2023
    profile: "baseload" # type of load profile (e.g., "baseload", "industry", "total_daily_avg", "total")
    share: 50 # share of CI load to be moved to high voltage level (to avoid negative values when profile is not "total")

  freeze_capacity: false
  filter_TYNDP_build_year: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#transmission_projects
transmission_projects:
  include:
    nep: false
  new_link_capacity: keep #keep or zero

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  transport: false
  heating: false
  biomass: false
  ammonia: false
  # methanol: false
  industry: false
  shipping: false
  aviation: false
  agriculture: false
  dac: false
  H2_network: false
  co2_network: false
  allam_cycle_gas: false
  imports:
    enable: false
  gas_distribution_grid: false
  cluster_heat_buses: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#costs
costs:
  year: 2030
  version: v0.10.1

  overwrites:
    fuel:
      OCGT: 31.98 # https://tradingeconomics.com/commodity/eu-natural-gas
      CCGT: 31.98
      gas: 31.98
      coal: 10.08 # https://www.tradingview.com/symbols/ICEEUR-ATW1!/ 1 USD = 0.88 EUR
      lignite: 22.11 # https://www.tradingview.com/symbols/ICEEUR-ATW1!/ 1 USD = 0.88 EUR, lignite ≈ 1/3 hard coal
    efficiency:
      Compressed-Air-Adiabatic-bicharger: 0.7745
    investment:
      iron-air battery: 21710  # in EUR/MWh (2020) from 23,500 EUR/MWh (2024)
      Compressed-Air-Adiabatic-store: 28835  # in EUR/MWh (2020) from 30,000 EUR/MWh (2022)
      Compressed-Air-Adiabatic-bicharger: 1658016  # in EUR/MW (2020) from 1,725,000 EUR/MW (2022)
    lifetime:
      Compressed-Air-Adiabatic-store: 40  # years
      Compressed-Air-Adiabatic-bicharger: 40  # years
  marginal_cost:
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 0.
    electrolysis: 0.
    fuel cell: 0.
    li-ion battery: 0.
    battery inverter: 0.
  capital_cost:
    geothermal: 10000
  emission_prices:
    enable: false
    co2: 64.85
    co2_monthly_prices: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering
clustering:
  temporal:
    resolution_sector: 3H

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#adjustments
adjustments:
  sector:
    absolute:
      links:
        DC:
          marginal_cost: 0.5
        electricity distribution grid:
          marginal_cost: 0.5

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#solving
solving:
  mem_mb: 300000 #50 GB is enough for vol-match 1 country, 150 GB is needed for multiple countries
  runtime: 24h #runtime in humanfriendly style https://humanfriendly.readthedocs.io/en/latest/

# ================ Procurment Metastudy ================
res_target:
  EU_share_target: true
  country_share_target: false
  country_cap_target: true
  res_additionality: false # select if the procured renewables are part of the RE target (false) or are in addition to it (true).
  res_path: data/ember_2030_res_targets.xlsx # path to EMBER 2030 global renewable target data (from https://storage.googleapis.com/emb-prod-bkt-publicdata/public-downloads/res_tracker/outputs/targets_download.xlsx)

grid_policy:
  renewable_carriers: ["offwind", "offwind-ac", "offwind-dc", "offwind-float", "onwind", "ror", "hydro", "urban central solid biomass CHP", "geothermal", "solar", "solar-hsat", "solar rooftop"]
  clean_carriers: ["offwind", "offwind-ac", "offwind-dc", "offwind-float", "onwind", "ror", "hydro", "urban central solid biomass CHP", "geothermal", "solar", "solar-hsat", "solar rooftop", "nuclear", "allam"]
  emitters: ["CCGT", "OCGT", "coal", "lignite", "oil"]

procurement:
  strategy: emi-match # name of procurement strategy: vol-match, emi-match, 247-cfe
  scope: "all" # "node", "country", "all", "continent"
  energy_matching: 100 # share of CI energy demand to be procured
  emissionality:
    emission_matching: 100 # share of CI emissions to be compensated
    emission_signal:  aer # type of emission signal: aer, mber, moer, cmer
    signal_source: model # source of emission signal: model, historical
    signal_model: data/emission-signals-model # folder path if aer, mber, or moer are chosen as emission_signal
    signal_historical: data/emission-signals-historical/2023_weighted_em_rates.csv # folder path if historical is chosen as emission_signal
  participation: 50 # share of CI load participating to the procurement

  technology:
    generation_tech: ["onwind", "offwind-ac", "offwind-dc", "offwind-float", "solar", "solar-hsat", "solar rooftop"]  # "allam", "geothermal", "nuclear"
    storage_tech: ["li-ion battery"] # "iron-air battery"

  strip_network: false # [ true, false ] If true, model only the countries with the CI loads and their neighbors
  strip_snapshots: false
  
  cap_premium: 1.1

  excess_share: 0.  # share of excess CI generation that can be sold to the grid [percentage]
  import_share: 1.
  min_iterations: 1

  ci:
    Albania:
      location: "AL0 0"
    Austria:
      location: "AT0 0"
    Bosnia and Herzegovina:
      location: "BA0 0"
    Belgium:
      location: "BE0 0"
    Bulgaria:
      location: "BG0 0"
    Switzerland:
      location: "CH0 0"
    Czech Republic:
      location: "CZ0 0"
    Germany:
      location: "DE0 0"
    Denmark:
      location: "DK0 0"
    Estonia:
      location: "EE0 0"
    Spain:
      location: "ES0 0"
    Finland:
      location: "FI1 0"
    France:
      location: "FR0 0"
    United Kingdom:
      location: "GB2 0"
    Greece:
      location: "GR0 0"
    Croatia:
      location: "HR0 0"
    Hungary:
      location: "HU0 0"
    Ireland:
      location: "IE3 0"
    Italy:
      location: "IT0 0"
    Lithuania:
      location: "LT0 0"
    Luxembourg:
      location: "LU0 0"
    Latvia:
      location: "LV0 0"
    Montenegro:
      location: "ME0 0"
    North Macedonia:
      location: "MK0 0"
    Netherlands:
      location: "NL0 0"
    Norway:
      location: "NO1 0"
    Poland:
      location: "PL0 0"
    Portugal:
      location: "PT0 0"
    Romania:
      location: "RO0 0"
    Serbia:
      location: "RS0 0"
    Sweden:
      location: "SE1 0"
    Slovenia:
      location: "SI0 0"
    Slovakia:
      location: "SK0 0"
    Kosovo:
      location: "XK0 0"

  
