# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

# ======== Baseline ==================================
# ====================================================

baseline-2025-1H: #1
  scenario:
    planning_horizons: 
    - 2025
  
  enable:
    procurement: false

  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')

  costs:
    year: 2025

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    EU_share_target: false
    country_cap_target: false

baseline-2030-1H: #2
  enable:
    procurement: false

  clustering:
    temporal:
      resolution_sector: 1H

baseline-2030-NoResTargets-1H: #3
  enable:
    procurement: false

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    EU_share_target: false
    country_cap_target: false

baseline-2030-scaled-load-1H: #4
  enable:
    procurement: false

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: false
    
  load:
    scaling_factor: 1.05

baseline-no-ci-2030-1H: #2
  enable:
    procurement: false

  remove_ci_load: 1

  clustering:
    temporal:
      resolution_sector: 1H

baseline-2030-NoResTargets-no-ci-1H: #3
  enable:
    procurement: false
  
  remove_ci_load: 1
  
  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    EU_share_target: false
    country_cap_target: false

baseline-25-no-ci-2030-1H: #2
  enable:
    procurement: false

  remove_ci_load: 0.5

  clustering:
    temporal:
      resolution_sector: 1H

baseline-2030-NoResTargets-25-no-ci-1H: #3
  enable:
    procurement: false
  
  remove_ci_load: 0.5
  
  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    EU_share_target: false
    country_cap_target: false

# ======== Annual volume matching =====================
# =====================================================

vol-match-2025-ci25-1H: #1
  scenario:
    planning_horizons: 
    - 2025
  
  enable:
    procurement: true
  
  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')

  costs:
    year: 2025

  clustering:
    temporal:
      resolution_sector: 1H
  
  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: vol-match
    scope: continent
    energy_matching: 100
    participation: 50

vol-match-2030-ci25-1H: #2
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: false

  procurement:
    strategy: vol-match
    scope: continent
    energy_matching: 100
    participation: 50

vol-match-2030-ci25-additional-1H: #2
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: true

  procurement:
    strategy: vol-match
    scope: continent
    energy_matching: 100
    participation: 50

vol-match-2030-country-ci25-1H: #3
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: false

  procurement:
    strategy: vol-match
    scope: country
    energy_matching: 100
    participation: 50

vol-match-2030-NoResTargets-ci25-1H: #4
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: vol-match
    scope: continent
    energy_matching: 100
    participation: 50

# ======== 247 CFE matching ============================
# ======================================================

247-cfe-2025-ci25-cfe90-1H: #1
  scenario:
    planning_horizons: 
    - 2025
  
  enable:
    procurement: true

  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')

  costs:
    year: 2025
  
  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: 247-cfe
    scope: node
    energy_matching: 90
    participation: 50

247-cfe-2025-ci25-cfe100-1H: #2
  scenario:
    planning_horizons: 
    - 2025
  
  enable:
    procurement: true

  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')

  costs:
    year: 2025
  
  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: 247-cfe
    scope: node
    energy_matching: 100
    participation: 50

247-cfe-2030-ci25-cfe90-1H: #3
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: false

  procurement:
    strategy: 247-cfe
    scope: node
    energy_matching: 90
    participation: 50

247-cfe-2030-ci25-cfe100-1H: #4
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: false

  procurement:
    strategy: 247-cfe
    scope: node
    energy_matching: 100
    participation: 50
    
247-cfe-2030-ci25-cfe70-1H: #3
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: false

  procurement:
    strategy: 247-cfe
    scope: node
    energy_matching: 70
    participation: 50

247-cfe-2030-ci25-cfe80-1H: #4
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: false

  procurement:
    strategy: 247-cfe
    scope: node
    energy_matching: 80
    participation: 50

247-cfe-2030-ci25-cfe90-additional-1H: #3
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: true

  procurement:
    strategy: 247-cfe
    scope: node
    energy_matching: 90
    participation: 50

247-cfe-2030-ci25-cfe100-additional-1H: #4
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: true

  procurement:
    strategy: 247-cfe
    scope: node
    energy_matching: 100
    participation: 50

247-cfe-2030-ci25-cfe90-additional-grid-1H: #3
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: true

  procurement:
    strategy: 247-cfe
    scope: node
    energy_matching: 90
    participation: 50
    min_iterations: 3

247-cfe-2030-ci25-cfe100-additional-grid-1H: #4
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: true

  procurement:
    strategy: 247-cfe
    scope: node
    energy_matching: 100
    participation: 50
    min_iterations: 3

# ======== Emission matching ==========================
# =====================================================

emi-match-2025-ci25-data-moer-1H: #1
  scenario:
    planning_horizons: 
    - 2025
  
  enable:
    procurement: true

  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')

  costs:
    year: 2025
  
  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: moer
      signal_source: historical

emi-match-2025-ci25-data-mber-1H: #2
  scenario:
    planning_horizons: 
    - 2025
  
  enable:
    procurement: true

  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')

  costs:
    year: 2025
  
  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: mber
      signal_source: historical

emi-match-2025-ci25-data-cmer-1H: #3
  scenario:
    planning_horizons: 
    - 2025
  
  enable:
    procurement: true

  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')

  costs:
    year: 2025
  
  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: cmer
      signal_source: historical

emi-match-2025-ci25-data-aer-1H: #4
  scenario:
    planning_horizons: 
    - 2025
  
  enable:
    procurement: true

  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')

  costs:
    year: 2025
  
  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: aer
      signal_source: historical

emi-match-2030-ci25-model-moer-1H: #5
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: moer
      signal_source: model

emi-match-2030-ci25-model-mber-1H: #6
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: mber
      signal_source: model

emi-match-2030-ci25-model-cmer-1H: #7
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: cmer
      signal_source: model

emi-match-2030-ci25-model-aer-1H: #8
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: false
    
  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: aer
      signal_source: model

emi-match-2030-ci25-model-moer-additional-1H: #5
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: true

  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: moer
      signal_source: model

emi-match-2030-ci25-model-mber-additional-1H: #6
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: true

  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: mber
      signal_source: model

emi-match-2030-ci25-model-cmer-additional-1H: #7
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: true

  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: cmer
      signal_source: model

emi-match-2030-ci25-model-aer-additional-1H: #8
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: true
    
  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: aer
      signal_source: model

emi-match-2030-ci25-model-lrmer_c-1H: #8
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: false
    
  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: lrmer_c
      signal_source: model

emi-match-2030-ci25-model-lrmer_c-additional-1H: #8
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    res_additionality: true
    
  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: lrmer_c
      signal_source: model

emi-match-2030-ci25-model-mber-no-res-1H: #6
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: mber
      signal_source: model

emi-match-2030-ci25-model-cmer-no-res-1H: #7
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: cmer
      signal_source: model

emi-match-2030-ci25-model-aer-no-res-1H: #8
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false
    
  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: aer
      signal_source: model

emi-match-2030-ci25-model-lrmer_c-no-res-1H: #8
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 1H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false
    
  procurement:
    strategy: emi-match
    scope: continent
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: lrmer_c
      signal_source: model