# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

# ======== Baseline ==================================
# ====================================================

baseline-2025-3H: #1
  enable:
    procurement: false

  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')
    freeze_capacity: true

  costs:
    year: 2025

  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    EU_share_target: false
    country_cap_target: false

baseline-2030-3H: #2
  enable:
    procurement: false

  clustering:
    temporal:
      resolution_sector: 3H

baseline-2030-NoResTargets-3H: #3
  enable:
    procurement: false

  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    EU_share_target: false
    country_cap_target: false

# ======== Annual volume matching =====================
# =====================================================

vol-match-2025-ci25-3H: #1
  enable:
    procurement: true
  
  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')
    freeze_capacity: true

  costs:
    year: 2025

  clustering:
    temporal:
      resolution_sector: 3H
  
  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: vol-match
    scope: "all"
    energy_matching: 100
    participation: 50

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"

vol-match-2030-ci25-3H: #2
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    res_additionality: false

  procurement:
    strategy: vol-match
    scope: "all"
    energy_matching: 100
    participation: 50

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"

vol-match-2030-country-ci25-3H: #3
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    res_additionality: false

  procurement:
    strategy: vol-match
    scope: "country"
    energy_matching: 100
    participation: 50

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"

vol-match-2030-NoResTargets-ci25-3H: #4
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: vol-match
    scope: "all"
    energy_matching: 100
    participation: 50

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"

vol-match-2030-ci25-continent-3H: #bonus
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 3H

  solving:
    mem_mb: 600000
    runtime: 48h

  res_target:
    res_additionality: false

  procurement:
    strategy: vol-match
    scope: "all"
    energy_matching: 100
    participation: 50

    ci:
      Albania:
        location: "AL0 0"
      Austria:
        location: "AT0 0"
      Bosnia and Herzegovina:
        location: "BA0 0"
      Belgium:
        location: "BE0 0"
      Bulgaria:
        location: "BG0 0"
      Switzerland:
        location: "CH0 0"
      Czech Republic:
        location: "CZ0 0"
      Germany:
        location: "DE0 0"
      Denmark:
        location: "DK0 0"
      Estonia:
        location: "EE0 0"
      Spain:
        location: "ES0 0"
      Finland:
        location: "FI1 0"
      France:
        location: "FR0 0"
      United Kingdom:
        location: "GB2 0"
      Greece:
        location: "GR0 0"
      Croatia:
        location: "HR0 0"
      Hungary:
        location: "HU0 0"
      Ireland:
        location: "IE3 0"
      Italy:
        location: "IT0 0"
      Lithuania:
        location: "LT0 0"
      Luxembourg:
        location: "LU0 0"
      Latvia:
        location: "LV0 0"
      Montenegro:
        location: "ME0 0"
      North Macedonia:
        location: "MK0 0"
      Netherlands:
        location: "NL0 0"
      Norway:
        location: "NO1 0"
      Poland:
        location: "PL0 0"
      Portugal:
        location: "PT0 0"
      Romania:
        location: "RO0 0"
      Serbia:
        location: "RS0 0"
      Sweden:
        location: "SE1 0"
      Slovenia:
        location: "SI0 0"
      Slovakia:
        location: "SK0 0"
      Kosovo:
        location: "XK0 0"

# ======== 247 CFE matching ============================
# ======================================================

247-cfe-2025-ci25-cfe90-3H: #1
  enable:
    procurement: true

  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')
    freeze_capacity: true

  costs:
    year: 2025
  
  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: 247-cfe
    scope: node
    energy_matching: 90
    participation: 50

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"

247-cfe-2025-ci25-cfe100-3H: #2
  enable:
    procurement: true

  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')
    freeze_capacity: true

  costs:
    year: 2025
  
  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: 247-cfe
    scope: node
    energy_matching: 100
    participation: 50

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"

247-cfe-2030-ci25-cfe90-3H: #3
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    res_additionality: false

  procurement:
    strategy: 247-cfe
    scope: node
    energy_matching: 90
    participation: 50

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"

247-cfe-2030-ci25-cfe100-3H: #4
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    res_additionality: false

  procurement:
    strategy: 247-cfe
    scope: node
    energy_matching: 100
    participation: 50

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"

# ======== Emission matching ==========================
# =====================================================

emi-match-2025-ci25-data-moer-3H: #1
  enable:
    procurement: true

  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')
    freeze_capacity: true

  costs:
    year: 2025
  
  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: "all"
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: moer
      signal_source: historical

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"

emi-match-2025-ci25-data-mber-3H: #2
  enable:
    procurement: true

  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')
    freeze_capacity: true

  costs:
    year: 2025
  
  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: "all"
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: mber
      signal_source: historical

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"

emi-match-2025-ci25-data-cmer-3H: #3
  enable:
    procurement: true

  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')
    freeze_capacity: true

  costs:
    year: 2025
  
  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: "all"
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: cmer
      signal_source: historical

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"

emi-match-2025-ci25-data-aer-3H: #4
  enable:
    procurement: true

  electricity:
    powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')
    freeze_capacity: true

  costs:
    year: 2025
  
  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    EU_share_target: false
    country_cap_target: false
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: "all"
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: aer
      signal_source: historical

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"

emi-match-2030-ci25-model-moer-3H: #5
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: "all"
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: moer
      signal_source: model

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"

emi-match-2030-ci25-model-mber-3H: #6
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: "all"
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: mber
      signal_source: model

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"

emi-match-2030-ci25-model-cmer-3H: #7
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    res_additionality: false

  procurement:
    strategy: emi-match
    scope: "all"
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: cmer
      signal_source: model

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"

emi-match-2030-ci25-model-moer-3H: #8
  enable:
    procurement: true

  clustering:
    temporal:
      resolution_sector: 3H

  res_target:
    res_additionality: false
    
  procurement:
    strategy: emi-match
    scope: "all"
    energy_matching: 100
    participation: 50
    emissionality:
      emission_matching: 100
      emission_signal: aer
      signal_source: model

    ci:
      Poland:
        location: "PL0 0"
      Germany:
        location: "DE0 0"
      France:
        location: "FR0 0"
      Spain:
        location: "ES0 0"
      Italy:
        location: "IT0 0"
      United Kingdom:
        location: "GB2 0"
